sqs:
  message_queue_interval: 10
  queues:
    default: &default
      AttributeNames:
        - all
      MaxNumberOfMessages: 1
      VisibilityTimeout: 100
      WaitTimeSeconds: 20
    messages:
      <<: *default
      MessageAttributeNames:
        - _id
        - method
        - adapter
        - castType
        - publisher
        - channel